apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qik2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0015-tenant/tkrw-pr712-0075-0015-app/devfile-sample-qik2@sha256:8ac3dd61527c52b48371b517dd898df34f7a5e6f776af314659ab0a61cf47a3d
        name: my-nodejs
        resources: {}
status: {}
